\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename vc-cmsyn.info
@settitle CM Synergy mode
@c %**end of header
     
@ifinfo
Copyright @copyright{} 2003  Realworld Systems.
@end ifinfo
@c @copying
@c Copyright 2003  Realworld Systems.
 
@c Author: Geert Ribbers <support@@realworldwide.com>
@c Created: May/2003
@c Updated: May/2003
 
@c This manual is free software; you can redistribute it and/or modify
@c it under the terms of the GNU General Public License as published by
@c the Free Software Foundation; either version 2, or (at your option)
@c any later version.
 
@c This manual is distributed in the hope that it will be useful,
@c but WITHOUT ANY WARRANTY; without even the implied warranty of
@c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
@c GNU General Public License for more details.
 
@c You should have received a copy of the GNU General Public License
@c along with GNU Emacs; see the manual COPYING.  If not, write to
@c the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
@c USA.
@c @end copying

@footnotestyle end

@dircategory GNU Emacs Lisp
@direntry
* CM Synergy Mode: (vc-cmsyn). CM Synergy integration for Emacs
@end direntry

@titlepage
@title CM Synergy mode for Emacs
@author Geert Ribbers

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@end titlepage
     
@node Top, Getting started, (dir), (dir)
@ifnottex 
@top CM Synergy mode for Emacs
@end ifnottex

CM Synergy mode for emacs integrates emacs with the Telelogic CM tool.
Files can be registered, checked in and out, history can be viewed, 
tasks can be selected.
Status-information is shown in the buffer's mode-line.
     
@menu
* Getting started:: Getting started
* Functionality::   Available Functionality
* Customization::   Customizing CM Synergy mode
* Patches::         Generating change-files based on differences with the base-line
* Restrictions/Limitations::    Restrictions and limitations that apply
* Concept Index::   Index
* Variable Index::  Index of Custom Variables
@end menu
@c * Copying::         Your rights and freedoms.

Author: Geert Ribbers, @uref{http://www.realworldwide.com,Realworld Systems}
@c @insertcopying

@node Getting started, Functionality, Top, Top
@chapter Getting started
@cindex getting started installation install

This chapter describes how to install CM Synergy mode and what's the first
step for using it

@enumerate

@item
Eventually unpack the archive.

@item 
Add directory @code{vc-cmsyn/lisp} to your @code{load-path};
@example
(setq load-path (cons <directory-path for this file> load-path))
@end example

@item 
Load the install file:
@example
(require 'vc-cmsyn-install)
@end example

@item 
If you want to use the patch-functionality, Load the patch-install file:
@example
(require 'vc-cmsyn-patch-install)
@end example

@item
Put the next line in the custom-set-variables section of your initialisation file (probably .emacs):
@example
 '(vc-cmsyn-auto-check-status-file-open-p t)
@end example

@item 
The CMSynergy menu is found in the menu-bar under Tools by default:
 CMSynergy@*
This can be customized by changing the value of custom-var @code{vc-cmsyn-menu-path} with the emacs-customization system or as shown above for @code{vc-cmsyn-auto-check-status-file-open-p})

@item 
Restart Emacs.

@item 
You may want to customize the mode:
Go to the menu-bar Tools/CMSynergy/Customize...
This brings up a customization buffer where you can adjust options to your personal preference.

@end enumerate
@xref{Customization}.

@node Functionality, Customization, Getting started, Top
@chapter Functionality

The CM Synergy menu lists the available functions.@*
It is available from the Menubar, the place depends on the value of the custom-option @code{vc-cmsyn-menu-path} (default it's in the Tools menu).
Some of the options are available through keyboard-shortcuts as well which is shown behind the description.@*
@enumerate
@item @ref{Login...}
@item @ref{Show Default Task}
@item @ref{Show Task Files}
@item @ref{Open Task Files}
@item @ref{Select Task}
@item @ref{Check Out This File}
@item @ref{Undo Check Out File}
@item @ref{Check Out This Directory}
@item @ref{Undo Check Out Directory}
@item @ref{Check In This File}
@item @ref{Register This File into CM Synergy}
@item @ref{Register This Directory into CM Synergy}
@item @ref{Check In Task}
@item @ref{Update Modeline}
@item @ref{Show Properties This File}
@item @ref{Show History}
@itemize @bullet
@item @ref{This File (graphics)}
@item @ref{This File (details)}
@item @ref{This Directory (graphics)}
@item @ref{This Directory (details)}
@end itemize
@item @ref{Compare}
@itemize @bullet
@item @ref{With Previous Version}
@item @ref{With other Version}
@item @ref{Versions}
@end itemize
@item @ref{Set CCM_ADDR}
@item @ref{Generate patch-file default task}
@item @ref{Generate patch-file...}
@item @ref{Load task changes default task}
@item @ref{Customize...}
@item @ref{Customize Admin...}
@item @ref{Help}
@itemize @bullet
@item @ref{Info...}
@item @ref{Html...}
@end itemize
@item @ref{About CMSynergy Mode...}

@end enumerate


@enumerate

@item Login... (C-c RET l)
@anchor{Login...}@*
Start a CM Synergy session@*
A CM Synergy session will be started, the result of the action will be shown in the CM Synergy Output Buffer.
The environment variable @code{CCM_ADDR} will be set to the value as received from CM Synergy.@*
Sample Output:@*
@quotation
Starting CM Synergy...@*
CM Synergy server starting on host pragem, using database \\computername\ccmdb\essent@*
@*
CM Synergy Release 6.2.3040 @*
@*
COPYRIGHT 2001 TELELOGIC AB.  All Rights Reserved.@*
This software is licensed and not sold.  All use of this software is@*
subject to the terms and conditions of the Telelogic AB@*
End User Software License, which should be read carefully.@*
This program is protected by U.S. and international copyright laws as@*
described in the "About CM Synergy" box.@*
@*
RESTRICTED RIGHTS LEGEND/NOTICE@*
@*
Use, duplication or disclosure by the government is subject to the@*
Restricted Rights restrictions as set forth in subparagraph (c)(1)(ii)@*
of the Rights in Technical Data and Computer Software clause at@*
DFARS 252.227-7013 or FAR 52.227-14, Alternate III,@*
subparagraph (g)(3)(i), each clause of current date.@*
@*
Telelogic AB, Malmo, Sweden@*
@*
CM Synergy ready...@*
CM Synergy address is ROOSPORTGEERT:1639:192.168.1.101.@*
@*
CM Synergy Command finished@*

@end quotation
@item Show Default Task (C-c RET d)
@anchor{Show Default Task}@*
This will popup the CM Synergy Output buffer and show which task is default.@*
Sample Output:@*
@quotation
Retrieving Current Default Task@*
@*
27: Fix for Task 26: Cableupdate@*
@*
CM Synergy Command finished@*
@end quotation

@item Show Task Files
@anchor{Show Task Files}@*
This will popup the CM Synergy Output buffer and show a list of files are involved in the default task.@*
Sample Output:@*
@quotation
Retrieving files for task 27: Fix for Task 26: SynopsisTest...@*
@*
1) collection_transfer.magik~1.1.3:majik:1 @*
2) collection_transferxxx~2:dir:1          @*
3) testgeert.magik~1:magik:1               @*
@*
CM Synergy Command finished@*
@end quotation

@item Open Task Files
@anchor{Open Task Files}@*
This will open the files belonging to the default task in emacs.@*
Restrictions apply: @xref{open-task-files-restriction}.

@item Select Task (C-c RET s)
@anchor{Select Task}@*
Popup the CM Synergy GUI with the task window allowing you to select a task.

@item Check Out This File (C-c RET o)
@anchor{Check Out This File}@*
This item is only active in a file-buffer within a CM Synergy Workarea.
Check out the current file from CM Synergy into writable state.@*
Sample Output:@*
@quotation
Starting check out of c:/users/geert/ccm_wa2/essent/beheer_components~geert.1.1/beheer_components/collection_transferxxx/collection_transfer.magik...@*
@*
Parallel versions exist for collection_transfer.magik~1.1.3:majik:1@*
Added 'release' attribute with value '310_4' to object collection_transfer.magik~1.1.4:majik:1@*
Warning: Parallel branches exist for collection_transfer.magik~1.1.4@*
Checked out new version 'collection_transfer.magik~1.1.4' from 'collection_transfer.magik~1.1.3'@*
Associated object collection_transfer.magik~1.1.4:majik:1 with task 27.@*
@*
CM Synergy Command finished@*
@end quotation

@item Undo Check Out File (C-c RET u)
@anchor{Undo Check Out File}@*
Brings the file back into the state before checkout, deleting the checked out version from CM Synergy.@*
Sample Output:@*
@quotation
Starting undo check out of c:/users/geert/ccm_wa2/essent/beheer_components~geert.1.1/beheer_components/collection_transferxxx/collection_transfer.magik...@*
@*
Member 'collection_transfer.magik~1.1.4' has been replaced by 'collection_transfer.magik~1.1.3'.@*
Object 'collection_transfer.magik~1.1.4:majik:1' has been deleted.@*
@*
CM Synergy Command finished@*
@end quotation

@item Check Out This Directory
@anchor{Check Out This Directory}@*
This item is only active in a file-buffer or in dired within a CM Synergy Workarea.
Check out the directory object from CM Synergy into writable state.

@item Undo Check Out Directory
@anchor{Undo Check Out Directory}@*
Brings the directory object back into the state before checkout, deleting the checked out version from CM Synergy.

@item Check In This File (C-c RET i) 
@anchor{Check In This File} @*
This item is only active in a file-buffer within a CM Synergy Workarea.
Check in the current file into CM Synergy into readonly (integrate) state.@*
Sample Output:@*
@quotation
Starting check in of c:/users/geert/ccm_wa2/essent/beheer_components~geert.1.1/beheer_components/collection_transferxxx/collection_transfer.magik...@*
@*
Warning: Parallel branches exist for collection_transfer.magik~1.1.3@*
Archiving collection_transfer.magik~1.1.3:source@*
Checked in 'collection_transfer.magik~1.1.3' to 'integrate'@*
Summary:@*
	0  skipped.@*
	1  succeeded.@*
	0  failed@*
@*
CM Synergy Command finished@*
@end quotation

@item Register This File into CM Synergy (C-c RET r)
@anchor{Register This File into CM Synergy} @*
When the option @code{vc-cmsyn-register-checks-in-p (Check a file in when registering?)} is set to t (default)
the file will be checked in at the same time, otherwise the file will be in
writable mode@*
Sample Output of registering a file *combined* with checkin:@*
@quotation
Starting registration of c:/users/geert/ccm_wa2/essent/beheer_components~geert.1.1/beheer_components/collection_transferxxx/collection_transfer_mods.magik...@*
@*
Added 'release' attribute with value '310_4' to object collection_transfer_mods.magik~1:magik:1@*
Associated object collection_transfer_mods.magik~1:magik:1 with task 27.@*
Added 'release' attribute with value '310_4' to object collection_transferxxx~3:dir:1@*
Associated object collection_transferxxx~3:dir:1 with task 27.@*
	Updating database with file 'c:\users\geert\ccm_wa2\essent\beheer_components~geert.1.1\beheer_components\collection_transferxxx\collection_transfer_mods.magik'...@*
Member collection_transfer_mods.magik~1 added to project beheer_components~geert.1.1@*
Archiving collection_transferxxx~3:source@*
@*
@*
Starting check in of c:/users/geert/ccm_wa2/essent/beheer_components~geert.1.1/beheer_components/collection_transferxxx/collection_transfer_mods.magik...@*
@*
Archiving collection_transfer_mods.magik~1:source@*
Checked in 'collection_transfer_mods.magik~1' to 'integrate'@*
Summary:@*
	0  skipped.@*
	1  succeeded.@*
	0  failed@*
@*
CM Synergy Command finished@*
@end quotation

@item Register This Directory into CM Synergy
@anchor{Register This Directory into CM Synergy} @*
This checks in both the current directory and the files in it, prompting for recursive registration.
When the option @code{vc-cmsyn-register-checks-in-p (Check a file in when registering?)} is set to t (default)
the files will be checked in at the same time, otherwise the files will be in
writable mode

@item Check In Task
@anchor{Check In Task} @*
Checks in the default task plus all the files belonging to the task that are still checked out.

@item Update Modeline
@anchor{Update Modeline} @*
Retrieves status information about the current file from CM Synergy, showing the actual status in the modeline.@*
Sample modeline:@*
@quotation
collection_transfer_mods.magik-1:integrate@*
@end quotation

@item Show Properties This File (C-c RET p)
@anchor{Show Properties This File} @*
Shows CM Synergy properties of the current file in the CM Synergy Output buffer.@*
Sample Output:@*
@quotation
Properties...@*
@*
name        : graphics_system.magik@*
version     : 1@*
owner       : geert@*
status      : integrate@*
type        : magik@*
create_time : woensdag 21 mei 2003 15:45:47@*
modify_time : woensdag 21 mei 2003 15:46:00@*
platform    : <void>@*
release     : 310_4@*
task        : 27@*
@*
CM Synergy Command finished@*
@end quotation

@item Show History
@anchor{Show History}@*
@itemize @bullet
@item This File (graphics) (C-c RET h)
@anchor{This File (graphics)}@*
Shows the history of the current file graphically within the CM Synergy GUI.

@item This File (details)
@anchor{This File (details)}@*
Shows the history of the current file detailed within the CM Synergy Output buffer.@*
Sample Output:@*
@quotation
Retrieving history...@*
@*
Object:  collection_transfer.magik~1 (majik:1)@*
Owner:   ccm_root@*
State:   released@*
Created: maandag 24 maart 2003 15:17:13@*
Task:    10@*
Comment:@*
@*
Predecessors:@*
Successors:@*
	collection_transfer.magik~2:majik:1@*
	collection_transfer.magik~1.1.1:majik:1@*
	collection_transfer.magik~1.2.1:majik:1@*
*****************************************************************************@*
Object:  collection_transfer.magik~2 (majik:1)@*
Owner:   geert@*
State:   integrate@*
Created: dinsdag 15 april 2003 12:03:13@*
Task:    19@*
Comment:@*
checkin from within CM Synergy@*
Predecessors:@*
	collection_transfer.magik~1:majik:1@*
Successors:@*
	collection_transfer.magik~3:majik:1@*
*****************************************************************************@*
@*
CM Synergy Command finished@*
@end quotation

@item This Directory (graphics)
@anchor{This Directory (graphics)}@*
Shows the history of the current directory graphically within the CM Synergy GUI.

@item This Directory (details)
@anchor{This Directory (details)}@*
Shows the history of the current directory detailed within the CM Synergy Output buffer.
@end itemize

@item Compare
@anchor{Compare}@*
@itemize @bullet
@item With Previous Version
@anchor{With Previous Version}@*
Shows the differences between the current file and it's predecessor with ediff.

@item With other Version
@anchor{With other Version}@*
Shows the differences between the current file and a prompted version with ediff.

@item Versions
@anchor{Versions}@*
Shows the differences of prompted versions of the current file with ediff.
@end itemize

@item Set CCM_ADDR
@anchor{Set CCM_ADDR} @*
When this item is activated in the admin-options (@ref{vc-cmsyn-enable-set-ccm-addr-p}), this will prompt for the 
value of the CCM_ADDR environment-variable and set it.
Note that at login this variable is set automatically by this mode to the value as
received from CM Synergy.@*
@xref{Admin Options}.

@item Generate patch-file default task
@anchor{Generate patch-file default task} @*
When patching is configured in the admin-options (@ref{vc-cmsyn-patch-functionality-p}), 
this will generate a patch-file with the differences between the last version and the
base-line-version of all files belonging to the default task.@*
@xref{Admin Options}.@*
@xref{Patches}.

@item Generate patch-file...
@anchor{Generate patch-file...} @*
When patching is configured in the admin-options (@ref{vc-cmsyn-patch-functionality-p}), 
this will generate a patch-file with the differences between the last version and the
base-line-version of all files belonging to a task @samp{that the user is prompted for}.@*
@xref{Admin Options}.@*
@xref{Patches}.

@item Load task changes default task
@anchor{Load task changes default task} @*
When patching is configured in the admin-options (@ref{vc-cmsyn-patch-functionality-p}), 
this will generate temporary patch-file(s) with the differences between the last version and the
base-line-version of all files belonging to the default task and loads them with function as
configured in the admin-options.@*
@xref{Admin Options}.@*
@xref{Patches}.

@item New hot-fix-file...
@anchor{New hot-fix-file...} @*
When patching is configured in the admin-options (@ref{vc-cmsyn-patch-functionality-p}), 
this will generate an empty patch-file in the patches directory to be filled by a developer with hotfix-source-code, not based on any existing source-file.@*
@xref{Admin Options}.@*
@xref{Patches}.

@item Jump to source from patch
@anchor{Jump to source from patch} @*
When patching is configured in the admin-options (@ref{vc-cmsyn-patch-functionality-p}), and being in a patch-file,
this will jump to the same spot in the source-file where the patch was generated from.@*
If there is more than 1 possibility for the original source-file (in different projects), the user will be prompted which one is desired.
@xref{Admin Options}.@*
@xref{Patches}.

@item Jump to patch from source
@anchor{Jump to patch from source} @*
When patching is configured in the admin-options (@ref{vc-cmsyn-patch-functionality-p}), and being in a CM Synergy controlled source-file,
this will check if the current spot in the source-file is present in a patch-file.@*
If there is more than 1 possibility for the patch-file (in case of parallel versions), all applicable patch-files are opened and the user is notified.
@xref{Admin Options}.@*
@xref{Patches}.

@item Customize...
@anchor{Customize...} @*
Brings up the Custmization Buffer for the User Options for CM Synergy mode.@*
@xref{User Options}.

@item Customize Admin...
@anchor{Customize Admin...} @*
When this item is activated in the admin-options (@ref{vc-cmsyn-customize-admin-button-p}), this will bring up the Customization Buffer for the Admin Options for CM Synergy mode.@*
@xref{Admin Options}.

@item Help
@anchor{Help}@*
@itemize @bullet
@item Info...
@anchor{Info...}@*
Brings up the Info-help for CM Synergy mode.

@item Html...
@anchor{Html...}@*
Brings up the HTML-help for CM Synergy mode in the default browser.
@end itemize

@item About CMSynergy Mode...
@anchor{About CMSynergy Mode...} @*
Prints version- and author information in the minibuffer.
@end enumerate

@c @node   Keyboard, Customization, Functionality, Top
@c @chapter Keyboard

@c Several functions are available through keys on the keyboard:
@c @itemize
@c @item
@c @code{C-c RET l} Login

@c @item
@c @code{C-c RET d} Show Default Task

@c @item
@c @code{C-c RET s} Select Task

@c @item
@c @code{C-c RET o} Check Out This File


@node  Customization, User Options, Functionality, Top
@chapter Customization
@cindex customize customization preferences options

This chapter describes how to customize CM Synergy mode to suit your wishes and needs.
Emacs customization variables are used.
These are divided in 2 groups of custom-variables govering the mode:
@code{vc-cmsyn-user (User Options)} and @code{vc-cmsyn-admin (Admin Options)}.
The 1st group deals with personal preferences, the 2nd with the way the mode works.

@menu
* User Options::         User Options
* Admin Options::        Administration Options
* Patch Admin Options::  Patch Administration Options
@end menu

The options should *not* be set with setq but by using the customisation system of emacs.
Call up customization buffers by using M-x customize-variable / customize-group and use the 
set- and save- buttons.
You may also want to take a look in the Options menu under Customize Emacs.
Alternatively edit the custom-set-variables section of your personal init file by hand and set
the options there.

@node  User Options, Admin Options, Customization, Customization
@chapter User Options
@c @cindex 

The user options are available from the Menubar and deal with purely personal preferences.
Every user may work with his / her own settings.

The options are:@*
@vtable @samp
@c @itemize @bullet
@item vc-cmsyn-buffer-frame-width
@itemx CM Synergy output buffer frame width
The default width of the CM Synergy output-buffer-frame.

@item vc-cmsyn-buffer-frame-height
@itemx CM Synergy output buffer frame height
The default height of the CM Synergy output-buffer-frame.

@item vc-cmsyn-command-end-jump-to-output-buffer-p
@itemx Jump to Output-buffer After Commands?
The default height of the CM Synergy output-buffer-frame.

@item vc-cmsyn-register-checks-in-p
@itemx Check a file in when registering? 
If this is non-nil registering a file into CM Synergy will check it in at the same time.

@item vc-cmsyn-iconify-frame-when-ccm-gui
@itemx Iconify emacs when selecting tasks? 
If this is non-nil registering a file into CM Synergy will check it in at the same time.

@item vc-cmsyn-menu-path
@itemx Menu Path for CM Synergy menu 
Indicates the place of the CM Synergy menu in the menu-bar (no elements -so nil- is at top).
@end vtable

@node  Admin Options, Patch Admin Options, User Options, Customization
@chapter Admin Options
@c @cindex 

The admin options are only available from the Menubar if configured so in an option (@ref{vc-cmsyn-customize-admin-button-p}).
You can put up a customization-buffer by means of: @*
M-x customize-group RET vc-cmsyn-admin RET.@*
Here the options are listed and you can manage te values here.
They deal with a correct working of CM Synergy mode and should be set by the system administrator.
Whenever CM Synergy is configured differently or when output strings from CM Synergy change (new versions e.g.), 
changes in these settings may be necessary.

The options are:@*
@vtable @samp
@item vc-cmsyn-check-default-task-set-p
@itemx Check for default task set? 
Boolean indicating if it has to be checked if a default task is set before performing a ccm update.

@item vc-cmsyn-query-create-file-type
@itemx Query File-type? 
Boolean indicating if type of file has to be queried before registering a file in ccm
Typically this will be organized within CM Synergy already so it goes automatically.

@item vc-cmsyn-query-create-file-version
@itemx Query File-version? 
Boolean indicating if version of file has to be queried before registering a file in ccm.
Typically this will be organized within CM Synergy already so it goes automatically.

@item vc-cmsyn-auto-check-status-file-open-p
@itemx Auto check status on file open? 
Indicates if CM Synergy status should be checked for on opening of files.
This will have to be switched on, otherwise file-status is not retrieved from CM Synergy when files are opened.

@item vc-cmsyn-buffer-name
@itemx CM Synergy output buffer name 
Name of buffer in which to log CM Synergy actions.

@item vc-cmsyn-exe-name
@itemx CM Synergy executable name 
The CM Synergy executable name

@item vc-cmsyn-version-object-separator
@itemx Project Version Object Separator 
The CM Synergy object-version separator.@*
This is configured in CM Synergy, separates object-name and version in 4-part-names.

@item vc-cmsyn-no-differences-found-string
@itemx No differences found string 
The string CM Synergy outputs for indicating that there are no differences when comparing releases.

@item vc-cmsyn-parallel-versions-string
@itemx String output by CM Synergy when a parallel version exists
String in CM Synergy output when a parallel version exists.

@item vc-cmsyn-already-checked-out-regexp
@itemx String output by CM Synergy when a writable file is tried to checkout 
Regexp for checking CM Synergy output to see if a file was checked out correctly.

@item vc-cmsyn-checked-out-status-list
@itemx String output by CM Synergy when a writable file is tried to checkout 
Regexp for checking CM Synergy output to see if a file was checked out correctly.

@item vc-cmsyn-enable-set-ccm-addr-p
@itemx CCM_ADDR button? 
@anchor{vc-cmsyn-enable-set-ccm-addr-p}Indicates if button for setting CCM_ADDR should should be enabled.

@item vc-cmsyn-customize-admin-button-p
@itemx Customize-admin-options button?
@anchor{vc-cmsyn-customize-admin-button-p}Determines if button for customizing admin-options should be present in CM Synergy-menu, default not, only allowed for specific users.

@end vtable

@node  Patch Admin Options, Patches, Admin Options, Customization
@chapter Patch Admin Options
@c @cindex 

The patch admin options are only available from the Menubar if configured so (@ref{vc-cmsyn-customize-admin-button-p}).
You can put up a customization-buffer by means of: @*
M-x customize-group RET vc-cmsyn-patch-admin RET.@*
Here the options are listed and you can manage te values here.
They deal with a correct working of CM Synergy (patch) mode and should be set by the system administrator.
Whenever CM Synergy is configured differently or when output strings from CM Synergy change (new versions e.g.), 
changes in these settings may be necessary.

The options are:@*
@vtable @samp
@item vc-cmsyn-patch-functionality-p
@itemx Patch-file-functionality-in-use? 
@anchor{vc-cmsyn-patch-functionality-p}Is the patch-file-functionality in use (default available for magik)? This has to be configured!

@item vc-cmsyn-patch-project
@itemx Patch-project 
@anchor{vc-cmsyn-patch-project}The patch-project for storing the patch-files: name~version.

@item vc-cmsyn-patch-hotfix-extensions
@itemx Patch-hotfix-extensions
List with possible extensions for hot-fix-patch-files (default just @code{magik}, for Smallworld Magik.

@item vc-cmsyn-patch-file-properties
@itemx Patch-file-properties
List with data needed for the generation of patch-files, keyed on @samp{patch-file-extension}.
@enumerate
@item
 File extension: extension for the patch-file (typically same af for the source-code-files), this identifies the right entry in this list.
@item
 Patch-file identification regexp: regexp that when it matches in a CM Synergy file indicates that the file is a patch-file.
@item
 Patch-mode write-hook: when supplied, this function is added to write-contents-hooks of a patch-file, the standard value is @code{vc-cmsyn-patch-mode-write-hook}, which will look for updating a Date Changed string with the current date.
@end enumerate

@item vc-cmsyn-patch-types
@itemx Patch Types 
@anchor{vc-cmsyn-patch-types}List with data needed for the generation of patch-files, keyed on @samp{source-file-extension}.
@enumerate
@item
 File extension: extension for the patch-file (typically same af for the source-code-files), this identifies the right entry in this list.
@item
 Expand-function needs to supply begin-and end position of complete source-code around point in the buffer where it's called (without arguments).
@item
@anchor{vc-cmsyn-patch-types|relative-path-patch-project} Relative path within project-work-area: the work-area is known via the project, the sub-directory-path should be defined with this entry (e.g. source).
@item
 Source-file-mode function: function to call to switch the source-code files in the right major-mode (like `magik-mode').
@item
 Patch-file-name function: function that generates the name for the patch-file, 1 parameter: task.
@item
 Regexp to match blank / commented code: regexp that is used to check for changes that are pure blanks / comments which will not be taken to the patch-file.
@item
 Format-string for file-section-start: this string is sent as 1st parameter to `format', the current-source-file being 2nd: inserted in patch-file
 as start-marker for patches from current source-file.
@item
 Format-string for file-section-end: this string is sent as 1st parameter to `format', the current-source-file being 2nd: inserted in patch-file
 as end-marker for patches from current source-file.
@item
 Regexp that matches the complete leaf-name of a patch-file of this type, used to identify files as being such a patch-file
@item
 Init-Function to call within a file-to-diff, to prepare the file for diff (may cleanup emtpy lines, comments, multiple blanks, ...)
@item
 Function to call after creating the patch-buffer, before code is being inserted
@item
 Function to call in patch-buffer *after* all code is inserted
@item
 Function to call in patch-buffer, before code for 1 specific file is inserted (after file-start-marker is inserted)
@item
 Function to call in patch-buffer, after all code for 1 specific file is inserted (before file-end-marker is inserted).
@item
 Patch file header generation function
@item
@anchor{vc-cmsyn-patch-types|load-function} Load function: (if any, @code{transmit-buffer-to-magik} in case of Smallworld)
@item
 Jump to original source function (if any)
@item
 Jump to patch-file function (if any)
@end enumerate

@end vtable

@node   Patches, Restrictions/Limitations, Patch Admin Options, Top
@chapter Patches
@cindex patches

Included in CM Synergy mode is a framework for generating patch-files: files with the changes compared with the base-line version.
The framework is default configured for @code{Smallworld Magik} files.

What happens is that a list is made of the files belonging to the current task.@*
Restrictions apply: @xref{patch-file-generation-restriction}.

Of those files the base-line version is retrieved.@*
From both versions a reformatted version is created first:@* 
all comment-lines are removed and all multiple-blanks that do not occur in strings are reduced to 1 blank.@*
Then both reformatted versions are diffed against each other.@*
With the diff output complete-code-blocks are created from the recent version and those blocks are copied into a patch-file.@*
There is 1 patch-file per task, each block for 1 file is marked with special comment-markers.@*
For every occurring file-extension different patch-files can be created.@*
E.g. for Smallworld Magik changes in both magik- and msg-files go into a <name>.magik file.

The patch-files may use the same file-header as in the normal code files is used, it may also be 1 specific for a patch-file.@*
This is configured for every occurring file-extension in the custom-variable @var{vc-cmsyn-patch-types} (@ref{vc-cmsyn-patch-types}).@*
Within a patch-file you can jump to the original source with @samp{F6 s}.@*
If the original file is in more than 1 project, the user will be prompted for the project.@*
Within a CM Synsergy controlled source-file you can jump to an evt. patch-file with @samp{F6 p}.@*
When the source is in more than 1 patch-file, all applicable files are opened.

The patch-files are placed in a special patch-project, defined in CM Synergy.@*
The place of this project is configured for Emacs in an option (@ref{vc-cmsyn-patch-project}).@*
The relative path within the patch-project is configured within @var{vc-cmsyn-patch-types} (@ref{vc-cmsyn-patch-types|relative-path-patch-project}).

A similar function as creating patch-files is present: Load Task Changes.@*
This does principally the same, only the patch-file is created as a temporary file, which is not registered in CM Synergy.@*
These temporary files are loaded with a function configured in @var{vc-cmsyn-patch-types} then (@ref{vc-cmsyn-patch-types|load-function}).

For configuration: @xref{Patch Admin Options}.

@c @cindex menu-bar menubar getting started installation install

@c @menu
@c * Installation::                Installation of ECB
@c * First steps::                 First steps after activating ECB first time
@c @end menu
     
@c @node First Chapter
@c @chapter First Chapter
     
@c @cindex first chapter
@c @cindex chapter, first

@node Restrictions/Limitations, Concept Index, Patches, Top
@chapter Restrictions/Limitations
@table @samp
@item vc integration
Although the name of the package is vc-cmsyn it is not integrated with vc (yet).
It merely indicates that this is the intention.
In this package sentinel is used in the most calls to Synergy, where vc doesn't offer
clear hooks for this. It can be integrated nevertheless but with more effort so it just hasn't 
been done yet.


@item Open task-files 
@anchor{open-task-files-restriction}Since it is possible that more than 1 version of a file belongs to 1 task, the files are filtered on being a leaf in history.
This means this currently only works with private workareas.@*
@ref{Open Task Files}

@item Patch-file generation 
@anchor{patch-file-generation-restriction}Since it is possible that more than 1 version of a file belongs to 1 task, the files are filtered on being a leaf in history.@*
This is only reliable when users work in private workareas!@*
Working with shared workareas it is possible that the same file has (a) newer version(s) for other tasks.@*
In this case it is not a leaf anymore for the current task.@*
The file would not be selected for generating a patch-file anymore!@*
@ref{Patches}

@end table

@node Concept Index, Variable Index, Restrictions/Limitations, Top
@appendix Concept Index
@printindex cp

@node Variable Index,  , Concept Index, Top
@appendix Variable Index
@printindex vr

@c @shortcontents
@c @contents

@bye
